apiVersion: apps/v1
kind: Deployment
tag: release-0.1.1
metadata:
  name: wechat-cs-backend
  namespace: biel-production
  labels:
    app: {? {.Values.metadata.name: ''} : ''}
spec:
  selector:
    matchLabels:
      app: {? {.Values.metadata.name: ''} : ''}
  replicas: 2
  template:
    metadata:
      labels:
        app: {? {.Values.metadata.name: ''} : ''}
    spec:
      containers:
        - name: {? {.Values.metadata.name: ''} : ''}
          image: bieldatalab/wechat-cs-backend:{{ .Values.tag }}
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: mariadb-galera.biel-db.svc.cluster.local
            - name: MYSQL_PORT
              value: '3306'
          envFrom:
            - secretRef:
                name: wechat-cs-backend-secrets
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 400m
              memory: 500Mi
          ports:
            - containerPort: 8088
      imagePullSecrets:
        - name: dockerhub-registry
