name:  Push Tag Pipeline
on:
  create:
    branches: 
      - master
jobs:
  Push_tag:
     if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     runs-on: ubuntu-latest
     steps:     
       - name: Dump GitHub context
         env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
         run: echo "$GITHUB_CONTEXT"
       - uses: actions/checkout@v2   
       - name: Extract Version
         id: lookupVersion
         uses: mikefarah/yq@master
         with:
          cmd: yq e '.spec.template.spec.containers[0].image' 'deployment/deployment.yaml'
       - name: Push Tag
         run: |
          git tag $(echo "${{ steps.lookupVersion.outputs.result }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          git push --tag
