name:  Push Tag Pipeline
on:
  pull_request:
    branches: 
      - master
    types: [closed]
jobs:
  Push_tag:
     if: ${{ github.event.pull_request.merged }}
     runs-on: ubuntu-latest
     steps:     
       - uses: actions/checkout@v2   
       - name: Extract Version
         id: lookupVersion
         uses: mikefarah/yq@master
         with:
          cmd: yq e '.spec.template.spec.containers[0].image' 'deployment/deployment.yaml'
       - name: show yq result
         run: echo Result is ${{ steps.lookupVersion.outputs.result }}
       - name: Push Tag
         id: image
         run: |
          IMAGE_ID=$FILES_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo $VERSION
          #echo VERSION=$VERSION
          #docker tag image $IMAGE_ID:$VERSION
          #docker push $IMAGE_ID:$VERSION
