name:  Taging Pipeline
on:
  pull_request_review:
    types: 
      - submitted
jobs:
  Add_tag:
     runs-on: ubuntu-latest
     steps:     
       - name: Dump GitHub context
         env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
         run: echo "$GITHUB_CONTEXT"
       - name: Dump job context
         env:
          JOB_CONTEXT: ${{ toJSON(job) }}
         run: echo "$JOB_CONTEXT"
       - name: Dump steps context
         env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
         run: echo "$STEPS_CONTEXT"
       - name: Dump runner context
         env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
         run: echo "$RUNNER_CONTEXT"
       - name: Dump strategy context
         env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
         run: echo "$STRATEGY_CONTEXT"
       - name: Dump matrix context
         env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
         run: echo "$MATRIX_CONTEXT"
       - uses: actions/checkout@v2  
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - name: Extract Version
         id: image
         run: |
          VERSION=release-$(echo "${{ github.event.pull_request.body }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          echo VERSION=$VERSION
          
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo "::set-output name=version::$VERSION"

       - name: YAML Update Actoin
         uses: fjogeleit/yaml-update-action@master
         with:
           valueFile: deployment/deployment.yaml
           propertyPath: spec.template.spec.containers.image
           value: ${{ steps.image.outputs.version }}
           updateFile: true
           branch: ${{ github.event.pull_request.head.ref }}
           message: 'Update Image Tag to ${{ steps.image.outputs.version }}' 
         
           

