name:  Taging Pipeline
on:
  pull_request_review:
    types: 
      - submitted
jobs:
  Get_review_body:
     runs-on: ubuntu-latest
     steps:     
       - run: echo "Event  ${{github.event}}"

      

