name:  Taging Pipeline
on:
  pull_request_review:
    types: 
      - submitted
jobs:
  Add_tag:
     runs-on: ubuntu-latest
     steps:     
       - uses: actions/checkout@v2  
       - name: Extract Version
         id: image
         run: |
          VERSION=$(echo "${{ github.event.pull_request.body }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          echo VERSION=$VERSION
       - name: YAML Update Actoin
         uses: fjogeleit/yaml-update-action@master
         with:
           valueFile: 'deployment/deployment.yaml'
           propertyPath: 'spec.template.spec.containers.image'
           value: 'test-version'
      

