name:  Taging Pipeline
on:
  pull_request_review:
    types: 
      - submitted
jobs:
  Add_tag:
     runs-on: ubuntu-latest
     steps:     
       - uses: actions/checkout@v2  
       - name: Extract Version
         id: image
         run: |
          TAG_NAME=$(echo "${{ github.event.pull_request.body }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "${{ github.base_ref }}"
          echo "${{ github.head_ref }}"
          echo $VERSION
          echo TAG_NAME=$TAG_NAME
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tag_name::$TAG_NAME"

       - name: YAML Update Actoin
         uses: swdotcom/update-and-apply-kubernetes-configs@v1
         with:
          k8-config-file-paths: 'deployment/deployment.yaml'
         env:
           IMAGE_TAG: ${{ steps.image.outputs.tag_name }}
         
           

