name:  Taging Pipeline

on:
  pull_request_review:
    types: [edited, submitted]

  
jobs:
  get_review_body:
     runs-on: ubuntu-latest
     steps:     
      - run: echo "Event  ${{github.event}}"

      

