name:  Taging Pipeline
on:
  pull_request_review:
    types: 
      - submitted
jobs:
  Add_tag:
     runs-on: ubuntu-latest
     steps:     
       - uses: actions/checkout@v2  
       - name: Extract Version
         id: image
         run: |
          VERSION=release-$(echo "${{ github.event.pull_request.body }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
       - name: Modify Yaml Tag
         uses: mikefarah/yq@master
         with:
          cmd: yq eval -i '.spec.template.spec.containers[0].image="bieldatalab/wechat-cs-backend:${{ steps.image.outputs.version }}"'       
       - name: Commit changes
         uses: EndBug/add-and-commit@v7
         with:
          author_name: Github
          author_email: Github@bielcrystal.com
          message: 'Update Image Tag to ${{ steps.image.outputs.version }}' 
          add: '*.yaml'

         
           

